version: "3"
services:
  node:
    build:
      context: ./app
    environment:
      - NODE_ENV=production
      - REACT_APP_NAME=ken-portfolio
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
